// Converts data/suzuka-centerline.csv (TUMFTM/racetrack-database, LGPL-3.0)
// into src/track/suzukaData.js. Run: node tools/convert-track.js
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const csv = fs.readFileSync(path.join(root, 'data/suzuka-centerline.csv'), 'utf8');

const rows = csv.trim().split('\n').filter(l => !l.startsWith('#'))
  .map(l => l.split(',').map(Number));

// Game coordinates: x = east, z = -north (three.js, +y up, north = -z when
// viewed from above with +x right). Round to cm.
const pts = rows.map(([x, y, wr, wl]) => [
  Math.round(x * 100) / 100,
  Math.round(-y * 100) / 100,
  Math.round(wr * 100) / 100,
  Math.round(wl * 100) / 100,
]);

const out = `// Suzuka Circuit centerline — generated by tools/convert-track.js. Do not edit.
// Source: TUMFTM/racetrack-database (https://github.com/TUMFTM/racetrack-database)
// License of source data: LGPL-3.0. Center line from smoothed OpenStreetMap
// GPS points; track widths extracted from satellite imagery (TUM FTM).
// Format per point: [x, z, widthRight, widthLeft] in meters, game coordinates
// (x = east, z = south, y-up added at runtime). Direction of travel: ascending
// index, clockwise (real race direction). Point 0 = start/finish line.
export const SUZUKA_POINTS = ${JSON.stringify(pts)};
`;
fs.writeFileSync(path.join(root, 'src/track/suzukaData.js'), out);
console.log(`wrote ${pts.length} points to src/track/suzukaData.js`);
